name: 'Build c4z'
description: 'Builds a c4z from a c4zproj in specified directory'
inputs:
  projectDir:
    description: 'Directory of project'
    required: true
  c4zproj:
    description: 'Name of c4zproj manifest'
    required: true
outputs:
  time:
    description: 'The time this ran'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.projectDir }}
    - ${{ inputs.c4zproj }}